version: '3.8'

services:
  db:
    image: mysql:8
    container_name: risWeb-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: risWeb_db
    ports:
      - "3309:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

  app:
    build: .
    container_name: vaja1Ris
    ports:
      - "8083:8080"
    environment:
       SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/risWeb_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
       SPRING_DATASOURCE_USERNAME: root
       SPRING_DATASOURCE_PASSWORD: root1234
       SPRING_JPA_HIBERNATE_DDL_AUTO: create

    depends_on:
     - db

volumes:
  db_data:
